name: Continuous Integration

on:
  push:
    branches:
      - main
jobs:
  sample-test:
    name: Test and deploy care flow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        id: install
        run: npm install

      - name: Test
        id: npm-test
        run: npm run test

      - name: Validate Care Flow Logic
        id: validate
        uses: awell-health/action-validate@v1.0.0-beta
        with:
          api_key: ${{ secrets.DEVELOPMENT_API_KEY }}
          awell_endpoint: https://api.development.awellhealth.com/design/m2m/graphql
          filename: validation.yaml
          careflow_id: xjUdrKvscUmq

      # Runs on successful tests ✅
      - name: Set published release as live
        id: set-live
        uses: awell-health/action-set-careflow-live@v1.0.0-beta
        with:
          api_key: ${{ secrets.DEVELOPMENT_API_KEY }}
          awell_environment: development
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print output
        id: output
        run: echo "Care flow with release ID ${{ steps.set-live.outputs.release_id }} is now live."
